# Generated by Django 5.1.6 on 2025-02-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('pickup_country', models.CharField(max_length=100)),
                ('pickup_city', models.CharField(max_length=100)),
                ('delivery_country', models.CharField(default='Bulgaria', max_length=100)),
                ('delivery_city', models.CharField(default='Sofia', max_length=100)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved')], default='pending_approval', max_length=20)),
                ('small_car_count', models.PositiveIntegerField(default=0)),
                ('big_car_count', models.PositiveIntegerField(default=0)),
                ('suv_count', models.PositiveIntegerField(default=0)),
                ('bus_count', models.PositiveIntegerField(default=0)),
                ('final_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
